# Generated by Django 5.0.2 on 2025-03-06 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_ccazureopenai_ccopenai"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ccusermailinfo",
            name="password",
        ),
        migrations.AddField(
            model_name="ccusermailinfo",
            name="access_token",
            field=models.TextField(blank=True, null=True, verbose_name="访问令牌"),
        ),
        migrations.AddField(
            model_name="ccusermailinfo",
            name="last_sync_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后同步时间"),
        ),
        migrations.AddField(
            model_name="ccusermailinfo",
            name="refresh_token",
            field=models.TextField(blank=True, null=True, verbose_name="刷新令牌"),
        ),
        migrations.AddField(
            model_name="ccusermailinfo",
            name="tenant_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Azure租户ID"
            ),
        ),
        migrations.AddField(
            model_name="ccusermailinfo",
            name="token_expires",
            field=models.DateTimeField(blank=True, null=True, verbose_name="令牌过期时间"),
        ),
        migrations.AlterField(
            model_name="ccusermailinfo",
            name="client_id",
            field=models.CharField(max_length=255, verbose_name="Azure客户端ID"),
        ),
        migrations.AlterField(
            model_name="ccusermailinfo",
            name="client_secret",
            field=models.CharField(max_length=255, verbose_name="Azure客户端密钥"),
        ),
        migrations.CreateModel(
            name="CCEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("message_id", models.CharField(max_length=255, verbose_name="邮件ID")),
                ("subject", models.CharField(max_length=1000, verbose_name="邮件主题")),
                ("sender", models.EmailField(max_length=255, verbose_name="发件人")),
                ("received_time", models.DateTimeField(verbose_name="接收时间")),
                ("content", models.TextField(verbose_name="邮件内容")),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已读")),
                (
                    "categories",
                    models.CharField(blank=True, max_length=255, verbose_name="邮件分类"),
                ),
                (
                    "importance",
                    models.CharField(
                        default="normal", max_length=50, verbose_name="重要性"
                    ),
                ),
                (
                    "has_attachments",
                    models.BooleanField(default=False, verbose_name="是否有附件"),
                ),
                (
                    "user_mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="core.ccusermailinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "邮件内容",
                "verbose_name_plural": "邮件内容",
                "db_table": "cc_email",
                "ordering": ["-received_time"],
            },
        ),
    ]
