# Generated by Django 5.0.2 on 2025-03-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_ccusermailinfo_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CCEmailClassifyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                ("description", models.TextField(verbose_name="规则描述")),
                ("sender_domains", models.JSONField(verbose_name="发件人域名列表")),
                ("subject_keywords", models.JSONField(verbose_name="主题关键词列表")),
                ("body_keywords", models.JSONField(verbose_name="正文关键词列表")),
                (
                    "min_attachments",
                    models.IntegerField(default=0, verbose_name="最小附件数"),
                ),
                (
                    "max_attachments",
                    models.IntegerField(blank=True, null=True, verbose_name="最大附件数"),
                ),
                (
                    "min_attachment_size",
                    models.BigIntegerField(default=0, verbose_name="最小附件大小"),
                ),
                (
                    "max_attachment_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="最大附件大小"
                    ),
                ),
                ("classification", models.CharField(max_length=100, verbose_name="分类")),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
            ],
            options={
                "verbose_name": "邮件分类规则",
                "verbose_name_plural": "邮件分类规则",
                "db_table": "cc_emailclassifyrule",
                "ordering": ["-priority"],
            },
        ),
        migrations.AddField(
            model_name="ccemail",
            name="attachment_count",
            field=models.IntegerField(default=0, verbose_name="附件数量"),
        ),
        migrations.AddField(
            model_name="ccemail",
            name="attachments_info",
            field=models.JSONField(blank=True, default=list, verbose_name="附件详细信息"),
        ),
        migrations.AddField(
            model_name="ccemail",
            name="total_attachment_size",
            field=models.BigIntegerField(default=0, verbose_name="附件总大小(字节)"),
        ),
    ]
