# Generated by Django 5.0.2 on 2025-03-08 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_ccemailclassifyrule_ccemail_attachment_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CCEmailForwardingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=500, verbose_name="邮件标题")),
                ("sender", models.CharField(max_length=255, verbose_name="发件人")),
                ("received_time", models.DateTimeField(verbose_name="接收时间")),
                ("classification", models.CharField(max_length=100, verbose_name="分类")),
                ("email_type", models.CharField(max_length=50, verbose_name="邮件类型")),
                ("forwarding_recipient", models.TextField(verbose_name="转发收件人")),
                (
                    "message_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="邮件ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "邮件转发日志",
                "verbose_name_plural": "邮件转发日志",
                "db_table": "cc_email_forwarding_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CCForwardingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                ("rule_type", models.CharField(max_length=1, verbose_name="规则类型")),
                ("email_type", models.CharField(max_length=50, verbose_name="邮件类型")),
                ("description", models.TextField(verbose_name="规则描述")),
                ("forward_message", models.TextField(verbose_name="转发消息")),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
            ],
            options={
                "verbose_name": "邮件转发规则",
                "verbose_name_plural": "邮件转发规则",
                "db_table": "cc_forwardingrule",
                "ordering": ["-priority"],
            },
        ),
        migrations.AlterModelOptions(
            name="ccazureopenai",
            options={
                "verbose_name": "Azure OpenAI",
                "verbose_name_plural": "Azure OpenAI",
            },
        ),
        migrations.AlterModelOptions(
            name="ccopenai",
            options={"verbose_name": "OpenAI", "verbose_name_plural": "OpenAI"},
        ),
        migrations.RemoveField(
            model_name="ccazureopenai",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ccazureopenai",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="ccopenai",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ccopenai",
            name="provider",
        ),
        migrations.AlterField(
            model_name="ccazureopenai",
            name="api_key",
            field=models.CharField(max_length=200, verbose_name="API密钥"),
        ),
        migrations.AlterField(
            model_name="ccazureopenai",
            name="api_version",
            field=models.CharField(
                default=20250309, max_length=50, verbose_name="API版本"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ccazureopenai",
            name="endpoint",
            field=models.CharField(max_length=200, verbose_name="API端点"),
        ),
        migrations.AlterField(
            model_name="ccazureopenai",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="ccazureopenai",
            name="name",
            field=models.CharField(max_length=100, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="ccazureopenai",
            name="temperature",
            field=models.FloatField(default=0.7, verbose_name="温度"),
        ),
        migrations.AlterField(
            model_name="ccopenai",
            name="api_key",
            field=models.CharField(max_length=200, verbose_name="API密钥"),
        ),
        migrations.AlterField(
            model_name="ccopenai",
            name="api_version",
            field=models.CharField(
                default="2023-03-15-preview", max_length=50, verbose_name="API版本"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ccopenai",
            name="endpoint",
            field=models.CharField(max_length=200, verbose_name="API端点"),
        ),
        migrations.AlterField(
            model_name="ccopenai",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="ccopenai",
            name="name",
            field=models.CharField(max_length=100, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="ccopenai",
            name="temperature",
            field=models.FloatField(default=0.7, verbose_name="温度"),
        ),
        migrations.AlterModelTable(
            name="ccopenai",
            table=None,
        ),
        migrations.CreateModel(
            name="CCForwardingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱地址")),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="core.ccforwardingrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "邮件转发地址",
                "verbose_name_plural": "邮件转发地址",
                "db_table": "cc_forwardingaddress",
            },
        ),
    ]
