# Generated by Django 5.0.2 on 2025-03-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_ccemailforwardinglog_ccforwardingrule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ccemail",
            name="classification_confidence",
            field=models.FloatField(
                blank=True, help_text="分类的置信度，范围 0-1", null=True, verbose_name="分类置信度"
            ),
        ),
        migrations.AddField(
            model_name="ccemail",
            name="classification_method",
            field=models.CharField(
                blank=True,
                help_text="使用的分类方法，如 decision_tree, llm, bert, fasttext, sequence, stepgo",
                max_length=50,
                null=True,
                verbose_name="分类方法",
            ),
        ),
        migrations.AddField(
            model_name="ccemail",
            name="classification_reason",
            field=models.TextField(
                blank=True, help_text="分类的详细理由或依据", null=True, verbose_name="分类理由"
            ),
        ),
        migrations.AddField(
            model_name="ccemail",
            name="classification_rule",
            field=models.CharField(
                blank=True,
                help_text="匹配的规则名称，适用于决策树分类",
                max_length=255,
                null=True,
                verbose_name="匹配规则",
            ),
        ),
        migrations.AlterField(
            model_name="ccazureopenai",
            name="api_version",
            field=models.CharField(
                default="2023-03-15-preview", max_length=50, verbose_name="API版本"
            ),
        ),
    ]
