# Generated by Django 5.0.2 on 2025-03-09 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_ccemail_classification_confidence_and_more"),
    ]

    operations = []
