# Generated by Django 5.0.2 on 2025-03-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_ccemailmonitorstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="ccemail",
            name="is_forwarded",
            field=models.BooleanField(
                default=False, help_text="邮件是否已经被转发", verbose_name="是否已转发"
            ),
        ),
        migrations.AddField(
            model_name="ccemail",
            name="is_processed",
            field=models.BooleanField(
                default=False, help_text="邮件是否已经被分类处理", verbose_name="是否已处理"
            ),
        ),
        migrations.AddField(
            model_name="ccemail",
            name="processed_time",
            field=models.DateTimeField(
                blank=True, help_text="邮件被处理的时间", null=True, verbose_name="处理时间"
            ),
        ),
        migrations.AlterField(
            model_name="ccemail",
            name="classification_rule",
            field=models.CharField(
                blank=True,
                help_text="匹配的规则名称",
                max_length=255,
                null=True,
                verbose_name="匹配规则",
            ),
        ),
    ]
